title: "Adam Salah Developer Blog"
description: "Technical insights, tutorials, and projects"
url: "https://teamworx365.com"
baseurl: ""

# Use supported GitHub Pages theme
theme: minima

# Minimal plugins
plugins:
  - jekyll-feed
