title: "Adam Salah"
description: "Full-Stack Developer & Technical Writer"
url: "https://teamworx365.com"
baseurl: ""

author:
  name: "Adam Salah"
  email: "adam@teamworx365.com"
github_username: adamsalah13

# Collections for automatic content discovery
collections:
  articles:
    output: true
    permalink: /articles/:name/
  howtos:
    output: true
    permalink: /howtos/:name/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins (GitHub Pages whitelist only)
plugins:
  - jekyll-feed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
