title: "Adam Salah Developer Blog"
description: "Technical insights, tutorials, and projects"
url: "https://teamworx365.com"
baseurl: ""
encoding: UTF-8

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

collections:
  articles:
    output: true
    permalink: /articles/:name/
  howtos:
    output: true
    permalink: /howtos/:name/
