title: "Adam Salah Developer Blog"
description: "Technical insights, tutorials, and projects"
url: "https://teamworx365.com"
baseurl: ""

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
